language: node_js
arch:
 - amd64
 - ppc64le
node_js:
  - 0.6
  - 0.8
  - 4
  - 5
  # dropped unsupport node versions on power arch
jobs: 
  exclude:
    - arch: ppc64le
      node_js: 0.6
    - arch: ppc64le
      node_js: '0.10'

notifications:
  email:
    - travis@sidelab.com
  irc: "irc.freenode.org#sidelab"
